name: Validate Pull Request Formatting
on:
  pull_request:
    branches: [ main ]
jobs:
    check_formatting:
      runs-on: ubuntu-latest
      name: Check Formatting
      steps:
        - uses: actions/checkout@v2
        - runs: |
            dotnet tool restore
            dotnet csharpier --check .
